name: .NET Core

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          dotnet-quality: 'preview'
      - name: Build with dotnet
        run: dotnet build --configuration Release
