name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build solution
        run: dotnet build -c Release Ustilz.sln

      - name: Package Ustilz.Api
        run: dotnet pack -c Release -o . src/Ustilz.Api/Ustilz.Api.csproj
    
      - name: Package Ustilz.AspNetCore
        run: dotnet pack -c Release -o . src/Ustilz.AspNetCore/Ustilz.AspNetCore.csproj
             
      - name: Package Ustilz.Attributes
        run: dotnet pack -c Release -o . src/Ustilz.Attributes/Ustilz.Attributes.csproj
    
      - name: Package Ustilz.Data
        run: dotnet pack -c Release -o . src/Ustilz.Data/Ustilz.Data.csproj
    
      - name: Package Ustilz.Extensions
        run: dotnet pack -c Release -o . src/Ustilz.Extensions/Ustilz.Extensions.csproj
    
      - name: Package Ustilz.Http
        run: dotnet pack -c Release -o . src/Ustilz.Http/Ustilz.Http.csproj
       
      - name: Package Ustilz.Json
        run: dotnet pack -c Release -o . src/Ustilz.Json/Ustilz.Json.csproj

      - name: Package Ustilz.Logging
        run: dotnet pack -c Release -o . src/Ustilz.Logging/Ustilz.Logging.csproj
        
      - name: Package Ustilz.Medias
        run: dotnet pack -c Release -o . src/Ustilz.Medias/Ustilz.Medias.csproj
        
      - name: Package Ustilz.Models
        run: dotnet pack -c Release -o . src/Ustilz.Models/Ustilz.Models.csproj
        
      - name: Package Ustilz.Parsers
        run: dotnet pack -c Release -o . src/Ustilz.Parsers/Ustilz.Parsers.csproj
        
      - name: Package Ustilz.Razor
        run: dotnet pack -c Release -o . src/Ustilz.Razor/Ustilz.Razor.csproj
        
      - name: Package Ustilz.StateMachine
        run: dotnet pack -c Release -o . src/Ustilz.StateMachine/Ustilz.StateMachine.csproj
        
      - name: Package Ustilz.Time
        run: dotnet pack -c Release -o . src/Ustilz.Time/Ustilz.Time.csproj
        
      - name: Package Ustilz.UI
        run: dotnet pack -c Release -o . src/Ustilz.UI/Ustilz.UI.csproj
        
      - name: Package Ustilz.Utils
        run: dotnet pack -c Release -o . src/Ustilz.Utils/Ustilz.Utils.csproj
        
      - name: Package Ustilz.Wtf
        run: dotnet pack -c Release -o . src/Ustilz.Wtf/Ustilz.Wtf.csproj
        
      - name: Package Ustilz.Xml
        run: dotnet pack -c Release -o . src/Ustilz.Xml/Ustilz.Xml.csproj

      - name: Package Ustilz.Network
        run: dotnet pack -c Release -o . src/Ustilz.Network/Ustilz.Network.csproj
        
      - name: Package Ustilz.Network
        run: dotnet pack -c Release -o . src/Ustilz.Network/Ustilz.Network.csproj
        
      - name: Publish
        run: dotnet nuget push "*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}

